version: "3.7"

services:
 wordpress:
  build: requirements/wordpress
  restart: on-failure

  env_file:
   - .env

  depends_on:
   - mariadb

  volumes:
   - ~/data/wp:/wordpress
   
  networks:
   - net

 nginx:
  build: requirements/nginx
  restart: on-failure

  env_file:
   - .env

  ports:
   - 443:443

  depends_on:
   - wordpress

  volumes:
   - ~/data/wp:/wordpress

  networks:
   - net


 mariadb:
  build: requirements/mariadb
  restart: on-failure

  env_file:
   - .env

  ports:
   - 4040:3306
   
  volumes:
   - ~/data/db:/var/lib/mysql

  networks:
   - net

networks:
 net:

volumes:
 db:
 wp:
