version: "3.7"

services:
 wordpress:
  build: requirements/wordpress
  restart: on-failure

#  stdin_open: true # docker run -i
#  tty: true        # docker run -t
#  restart: always

  env_file:
   - .env

#  depends_on:
#   - mariadb

  volumes:
   - testcep-wp:/wordpress

  networks:
   - testcep


 nginx:
  build: requirements/nginx
  restart: on-failure

  env_file:
   - .env 
#  stdin_open: true # docker run -i
#  tty: true        # docker run -t

  ports:
   - 443:443

  depends_on:
   - wordpress

  volumes:
   - testcep-wp:/wordpress
   - ./requirements/nginx/log:/var/log/nginx 

  networks:
   - testcep



 mariadb:
  build: requirements/mariadb
  restart: on-failure

  env_file:
   - .env

  stdin_open: true # docker run -i
  tty: true        # docker run -t

#  volumes:
#   - testcep-db:/var/lib/mysql

  ports:
   - 4040:3306

  networks:
   - testcep

# testmariadb:
#  image: mariadb
#  restart: on-failure
#
#  volumes:
#   - testcep-db:/var/lib/mysql
#
#  ports:
#   - 4040:3306
#
#  networks:
#   testcep:


networks:
 testcep:

volumes:
 testcep-db:
 testcep-wp: