# syntax=docker/dockerfile:1
FROM alpine

ARG WP_SCRIPT="prep_wordpress.sh"

ARG DB_NAME="new_wp"
ARG DB_USER="example-user"
ARG DB_PASSWORD="my_cool_secret"
ARG DB_HOST="testmariadb"

COPY $WP_SCRIPT .
RUN dos2unix $WP_SCRIPT
RUN sh $WP_SCRIPT && rm $WP_SCRIPT

WORKDIR wordpress
COPY wp-config.php .

RUN apk add php-mysqli php-fpm php-json
#RUN apk add php php-bcmath php-cli php-common php-curl php-gd php-intl php-mbstring php-opcache php-soap php-sqlite3 php-xml php-xmlrpc php-xsl php-zip php-common
COPY php.ini /etc/php7/
COPY www.conf /etc/php7/php-fpm.d/

RUN adduser -S www-data
#RUN addgroup -S www-data

WORKDIR /etc/init.d
CMD ["php-fpm7", "--nodaemonize"]
